// <auto-generated />
using System;
using FMVideoManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMVideoManagerApi.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260603195328_StorageReferenceSupportLocalProvider")]
    partial class StorageReferenceSupportLocalProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("FMVideoManagerApi.Models.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("PK_user");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("UQ_user_login");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.CloudProviderAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("access_token_encrypted");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSyncAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_sync_at_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_account_id");

                    b.Property<string>("RefreshTokenEncrypted")
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<string>("Scopes")
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes");

                    b.Property<DateTime?>("TokenExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("token_expires_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_cloud_provider_account");

                    b.HasIndex("UserId", "Provider", "ProviderAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_cloud_provider_account_user_provider_account");

                    b.ToTable("cloud_provider_account", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.FileContent", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Hash")
                        .HasName("PK_file_content");

                    b.HasIndex("SizeBytes")
                        .HasDatabaseName("IX_file_content_size_bytes");

                    b.ToTable("file_content", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.FileItem", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("node_id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_filename");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("NodeId")
                        .HasName("PK_file_item");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_file_item_content_hash");

                    b.ToTable("file_item", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.GroupItem", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("node_id");

                    b.Property<string>("BackgroundColorHex")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("background_color_hex");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ForegroundColorHex")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("foreground_color_hex");

                    b.HasKey("NodeId")
                        .HasName("PK_group_item");

                    b.ToTable("group_item", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.HierarchyNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("node_type");

                    b.Property<long?>("ParentNodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_node_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_hierarchy_node");

                    b.HasAlternateKey("Id", "UserId")
                        .HasName("UQ_hierarchy_node_id_user");

                    b.HasIndex("ParentNodeId")
                        .HasDatabaseName("IX_hierarchy_node_parent_node_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_hierarchy_node_title");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_hierarchy_node_user_id");

                    b.HasIndex("ParentNodeId", "UserId");

                    b.HasIndex("UserId", "NodeType")
                        .HasDatabaseName("IX_hierarchy_node_user_type");

                    b.HasIndex("UserId", "ParentNodeId")
                        .HasDatabaseName("IX_hierarchy_node_user_parent");

                    b.ToTable("hierarchy_node", null, t =>
                        {
                            t.HasCheckConstraint("CK_hierarchy_node_not_self_parent", "parent_node_id IS NULL OR parent_node_id <> id");

                            t.HasCheckConstraint("CK_hierarchy_node_type", "node_type IN ('Group', 'File')");
                        });
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.NodeAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("node_id");

                    b.HasKey("Id")
                        .HasName("PK_node_alias");

                    b.HasIndex("Alias")
                        .HasDatabaseName("IX_node_alias_alias");

                    b.HasIndex("NodeId", "Alias")
                        .IsUnique()
                        .HasDatabaseName("UQ_node_alias_node_alias");

                    b.ToTable("node_alias", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.NodeTag", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("node_id");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("NodeId", "TagId")
                        .HasName("PK_node_tag");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_node_tag_node_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_node_tag_tag_id");

                    b.HasIndex("NodeId", "UserId");

                    b.HasIndex("TagId", "UserId");

                    b.HasIndex("UserId", "TagId")
                        .HasDatabaseName("IX_node_tag_user_tag");

                    b.ToTable("node_tag", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.StorageReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("CloudProviderAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cloud_provider_account_id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long?>("FileNodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_node_id");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderItemId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_item_id");

                    b.Property<DateTime?>("ProviderModifiedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_modified_at_utc");

                    b.Property<string>("ProviderPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_path");

                    b.Property<string>("ProviderRevision")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_revision");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_storage_reference");

                    b.HasIndex("CloudProviderAccountId")
                        .HasDatabaseName("IX_storage_reference_cloud_provider_account_id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_storage_reference_content_hash");

                    b.HasIndex("FileNodeId")
                        .HasDatabaseName("IX_storage_reference_file_node_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_storage_reference_user_id");

                    b.HasIndex("CloudProviderAccountId", "ProviderItemId")
                        .IsUnique()
                        .HasDatabaseName("UQ_storage_reference_cloud_account_provider_item")
                        .HasFilter("cloud_provider_account_id IS NOT NULL");

                    b.HasIndex("Provider", "ProviderItemId")
                        .HasDatabaseName("IX_storage_reference_provider_item");

                    b.HasIndex("UserId", "Provider", "ProviderItemId")
                        .IsUnique()
                        .HasDatabaseName("UQ_storage_reference_local_user_provider_item")
                        .HasFilter("provider = 'Local'");

                    b.ToTable("storage_reference", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundColorHex")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("background_color_hex");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ForegroundColorHex")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("foreground_color_hex");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_tag");

                    b.HasAlternateKey("Id", "UserId")
                        .HasName("UQ_tag_id_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_tag_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_tag_user_name");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.TagAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_tag_alias");

                    b.HasIndex("TagId", "UserId");

                    b.HasIndex("UserId", "Alias")
                        .IsUnique()
                        .HasDatabaseName("UQ_tag_alias_user_alias");

                    b.ToTable("tag_alias", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.CloudProviderAccount", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.AppUser", "User")
                        .WithMany("CloudProviderAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cloud_provider_account_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.FileItem", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.FileContent", "Content")
                        .WithMany("FileItems")
                        .HasForeignKey("ContentHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_file_item_content");

                    b.HasOne("FMVideoManagerApi.Models.HierarchyNode", "Node")
                        .WithOne("FileItem")
                        .HasForeignKey("FMVideoManagerApi.Models.FileItem", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_file_item_node");

                    b.Navigation("Content");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.GroupItem", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.HierarchyNode", "Node")
                        .WithOne("GroupItem")
                        .HasForeignKey("FMVideoManagerApi.Models.GroupItem", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_group_item_node");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.HierarchyNode", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.AppUser", "User")
                        .WithMany("HierarchyNodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_hierarchy_node_user");

                    b.HasOne("FMVideoManagerApi.Models.HierarchyNode", "ParentNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentNodeId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_hierarchy_node_parent_same_user");

                    b.Navigation("ParentNode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.NodeAlias", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.HierarchyNode", "Node")
                        .WithMany("Aliases")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_node_alias_node");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.NodeTag", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.HierarchyNode", "Node")
                        .WithMany("NodeTags")
                        .HasForeignKey("NodeId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_node_tag_node");

                    b.HasOne("FMVideoManagerApi.Models.Tag", "Tag")
                        .WithMany("NodeTags")
                        .HasForeignKey("TagId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_node_tag_tag");

                    b.Navigation("Node");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.StorageReference", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.CloudProviderAccount", "CloudProviderAccount")
                        .WithMany("StorageReferences")
                        .HasForeignKey("CloudProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_storage_reference_cloud_provider_account");

                    b.HasOne("FMVideoManagerApi.Models.FileContent", "Content")
                        .WithMany("StorageReferences")
                        .HasForeignKey("ContentHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_storage_reference_content");

                    b.HasOne("FMVideoManagerApi.Models.FileItem", "FileItem")
                        .WithMany("StorageReferences")
                        .HasForeignKey("FileNodeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_storage_reference_file_item");

                    b.HasOne("FMVideoManagerApi.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_storage_reference_user");

                    b.Navigation("CloudProviderAccount");

                    b.Navigation("Content");

                    b.Navigation("FileItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.Tag", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.AppUser", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tag_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.TagAlias", b =>
                {
                    b.HasOne("FMVideoManagerApi.Models.Tag", "Tag")
                        .WithMany("Aliases")
                        .HasForeignKey("TagId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tag_alias_tag");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.AppUser", b =>
                {
                    b.Navigation("CloudProviderAccounts");

                    b.Navigation("HierarchyNodes");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.CloudProviderAccount", b =>
                {
                    b.Navigation("StorageReferences");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.FileContent", b =>
                {
                    b.Navigation("FileItems");

                    b.Navigation("StorageReferences");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.FileItem", b =>
                {
                    b.Navigation("StorageReferences");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.HierarchyNode", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("ChildNodes");

                    b.Navigation("FileItem");

                    b.Navigation("GroupItem");

                    b.Navigation("NodeTags");
                });

            modelBuilder.Entity("FMVideoManagerApi.Models.Tag", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("NodeTags");
                });
#pragma warning restore 612, 618
        }
    }
}
