// <auto-generated />
using System;
using FMVideoManagerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMVideoManagerApp.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260521203000_InitialLocalCreate")]
    partial class InitialLocalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("FMVideoManagerApp.Models.Local.LocalFileLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<bool>("ExistsOnDisk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("exists_on_disk");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_utc");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_utc");

                    b.Property<long?>("LocalIndexedPathId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("local_indexed_path_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long?>("ServerFileItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_file_item_id");

                    b.Property<long>("ServerUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_user_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id")
                        .HasName("PK_local_file_location");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_local_file_location_content_hash");

                    b.HasIndex("LocalIndexedPathId");

                    b.HasIndex("ServerFileItemId")
                        .HasDatabaseName("IX_local_file_location_server_file_item_id");

                    b.HasIndex("ServerUserId", "Path")
                        .IsUnique()
                        .HasDatabaseName("UQ_local_file_location_user_path");

                    b.ToTable("local_file_location", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApp.Models.Local.LocalIndexedPath", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IncludeSubdirectories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("include_subdirectories");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastScannedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scanned_at_utc");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long>("ServerUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_user_id");

                    b.HasKey("Id")
                        .HasName("PK_local_indexed_path");

                    b.HasIndex("ServerUserId", "Path")
                        .IsUnique()
                        .HasDatabaseName("UQ_local_indexed_path_user_path");

                    b.ToTable("local_indexed_path", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApp.Models.Local.PreviewCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<DateTime>("LastAccessedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_accessed_at_utc");

                    b.Property<string>("PreviewPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_path");

                    b.Property<long?>("ServerFileItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_file_item_id");

                    b.Property<long>("ServerUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("PK_preview_cache");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_preview_cache_content_hash");

                    b.HasIndex("PreviewPath")
                        .IsUnique()
                        .HasDatabaseName("UQ_preview_cache_path");

                    b.HasIndex("ServerFileItemId")
                        .HasDatabaseName("IX_preview_cache_server_file_item_id");

                    b.ToTable("preview_cache", (string)null);
                });

            modelBuilder.Entity("FMVideoManagerApp.Models.Local.LocalFileLocation", b =>
                {
                    b.HasOne("FMVideoManagerApp.Models.Local.LocalIndexedPath", "LocalIndexedPath")
                        .WithMany()
                        .HasForeignKey("LocalIndexedPathId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_local_file_location_indexed_path");

                    b.Navigation("LocalIndexedPath");
                });
#pragma warning restore 612, 618
        }
    }
}
